version: '1.0.{build}'
skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\\Python34"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "x32"
      ARCH: "x86"
      BUILD_PLATFORM: "win32"
      PYTHON_VERSION: "34"
    - PYTHON: "C:\\Python34-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "x64"
      ARCH: "x64"
      BUILD_PLATFORM: "x64"
      PYTHON_VERSION: "34-x64"
    - PYTHON: "C:\\Python35"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "x32"
      ARCH: "x86"
      BUILD_PLATFORM: "win32"
      PYTHON_VERSION: "35"
    - PYTHON: "C:\\Python35-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "x64"
      ARCH: "x64"
      BUILD_PLATFORM: "x64"
      PYTHON_VERSION: "35-x64"
    - PYTHON: "C:\\Python36"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "x32"
      ARCH: "x86"
      BUILD_PLATFORM: "win32"
      PYTHON_VERSION: "36"
    - PYTHON: "C:\\Python36-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "x64"
      ARCH: "x64"
      BUILD_PLATFORM: "x64"
      PYTHON_VERSION: "36-x64"

install:
# If there is a newer build queued for the same PR, cancel this one.
# The AppVeyor 'rollout builds' option is supposed to serve the same
# purpose but it is problematic because it tends to cancel builds pushed
# directly to master instead of just PR builds (or the converse).
# credits: JuliaLang developers.
- ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
    https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
    Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
- cmd: >-
    git submodule update --init --recursive

build_script:
- cmd: |-

    if not exist "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR%" mkdir "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR%"
    
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %ARCH%
    
    set "INCLUDE=%PYTHON%\include;%INCLUDE%"
    set "LIB=%PYTHON%\libs;%LIB%"

    echo %INCLUDE%
    echo %LIB%

    msbuild RainmeterPython.vcxproj /p:configuration=release /p:platform=%BUILD_PLATFORM% /p:useenv=true /v:d
    
    mkdir release-dlls
    xcopy "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR%\release\*.dll" .\release-dlls\ /I

deploy:
  release: Rainmeter-Python-v$(appveyor_build_version)
  description: 'Automated Build Release'
  provider: GitHub
  auth_token:
    secure: olbMvHpayGgqvdAdimUIJQ5W33juPyQ3jU+UgIEr81pZq8qt5S+U+crMr1kmEWD6
  artifact: RainmeterPython-v$(appveyor_build_version)-Python$(PYTHON_VERSION)
artifacts:
- path: release-dlls
  name: RainmeterPython-v$(appveyor_build_version)-Python$(PYTHON_VERSION)
