environment:
  matrix:
    - PYTHON: "C:\\Python34"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      BUILD_PLATFORM: "win32"
      PYTHON_VERSION: "3.4"
    - PYTHON: "C:\\Python34-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      BUILD_PLATFORM: "x64"
      PYTHON_VERSION: "3.4"
    - PYTHON: "C:\\Python35"
      BUILD_ENV: "Visual Studio 14"
      BUILD_DIR: "build"
      BUILD_PLATFORM: "win32"
      PYTHON_VERSION: "3.5"
    - PYTHON: "C:\\Python35-x64"
      BUILD_ENV: "Visual Studio 14 Win64"
      BUILD_DIR: "build64"
      BUILD_PLATFORM: "x64"
      PYTHON_VERSION: "3.5"

install:
- cmd: >-
    git submodule update --init --recursive

build_script:
- cmd: |-

    if not exist "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR%" mkdir "%APPVEYOR_BUILD_FOLDER%\%BUILD_DIR%"
    
    set "INCLUDE=%PYTHON%\include;%INCLUDE%"

    echo %INCLUDE%

    msbuild RainmeterPython.vcxproj /p:configuration=release /p:platform=%BUILD_PLATFORM% /p:AdditionalLibPaths="%PYTHON%\libs" /v:d
    
    mkdir release-dlls
    xcopy "%APPVEYOR_BUILD_FOLDER%\opencv\%BUILD_DIR%\bin\Release\*.dll" .\release-dlls\ /I

artifacts:
- path: release-dlls
  name: dlls